#!/usr/bin/env bash
# Regenera src/integrations/supabase/types.ts a partir do schema atual do banco.
#
# Uso:
#   npm run db:types
#
# Modos (o script escolhe automaticamente):
#   1) Conexão direta ao Postgres  -> usa $SUPABASE_DB_URL ou as variáveis PG* (PGHOST, PGUSER, ...)
#   2) API do Supabase             -> usa $SUPABASE_ACCESS_TOKEN + project id (.env: VITE_SUPABASE_PROJECT_ID)
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="src/integrations/supabase/types.ts"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# carrega .env (sem sobrescrever variáveis já exportadas)
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
fi

SUPA="npx --yes supabase@latest"

has_docker() { command -v docker >/dev/null 2>&1 || command -v podman >/dev/null 2>&1; }

if [ -n "${SUPABASE_ACCESS_TOKEN:-}" ] && [ -n "${VITE_SUPABASE_PROJECT_ID:-}" ]; then
  echo "→ Gerando tipos via API (project ${VITE_SUPABASE_PROJECT_ID})..."
  $SUPA gen types typescript --project-id "$VITE_SUPABASE_PROJECT_ID" --schema public > "$TMP"
elif has_docker && [ -n "${SUPABASE_DB_URL:-}" ]; then
  echo "→ Gerando tipos via SUPABASE_DB_URL..."
  $SUPA gen types typescript --db-url "$SUPABASE_DB_URL" --schema public > "$TMP"
elif has_docker && [ -n "${PGHOST:-}" ] && [ -n "${PGUSER:-}" ]; then
  echo "→ Gerando tipos via variáveis PG*..."
  DB_URL="postgresql://${PGUSER}:${PGPASSWORD:-}@${PGHOST}:${PGPORT:-5432}/${PGDATABASE:-postgres}"
  $SUPA gen types typescript --db-url "$DB_URL" --schema public > "$TMP"
else
  echo "ERRO: nao foi possivel gerar os tipos." >&2
  echo "Opcao A (recomendada, sem Docker): export SUPABASE_ACCESS_TOKEN=<token da sua conta Supabase>" >&2
  echo "  (VITE_SUPABASE_PROJECT_ID ja vem do .env)" >&2
  echo "Opcao B: instalar Docker/Podman e definir SUPABASE_DB_URL (ou PGHOST/PGUSER/PGPASSWORD)." >&2
  exit 1
fi

if [ ! -s "$TMP" ] || ! grep -q "export type Database" "$TMP"; then
  echo "ERRO: saída inválida — types.ts NÃO foi alterado." >&2
  exit 1
fi

{
  echo "// This file is automatically generated. Do not edit it directly."
  echo "// Regenerate with: npm run db:types"
  cat "$TMP"
} > "$OUT"

echo "✔ $OUT atualizado ($(wc -l < "$OUT") linhas)."
