// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista projetos do sistema AG, com filtro opcional por texto (nome/c\xF3digo) e por status de execu\xE7\xE3o.",
  inputSchema: {
    search: z.string().trim().optional().describe("Texto para buscar em nome ou c\xF3digo do projeto."),
    execution_status: z.string().trim().optional().describe("Filtra por execution_status exato (ex: em_campo, entregue, faturamento)."),
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de projetos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, execution_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id, codigo, name, service, status, execution_status, contract_value, client_id, delivery_deadline").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,codigo.ilike.%${search}%`);
    if (execution_status) query = query.eq("execution_status", execution_status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Detalhe do projeto",
  description: "Retorna os dados completos de um projeto pelo c\xF3digo (ex: 2026-AGT-001) ou pelo id.",
  inputSchema: {
    codigo: z2.string().trim().optional().describe("C\xF3digo do projeto."),
    id: z2.string().uuid().optional().describe("UUID do projeto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ codigo, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    if (!codigo && !id) {
      return { content: [{ type: "text", text: "Informe codigo ou id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("codigo", codigo);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Projeto n\xE3o encontrado." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes cadastrados, com busca opcional por nome, c\xF3digo de 3 letras ou CNPJ.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Texto para buscar em nome, c\xF3digo ou CNPJ."),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, codigo, name, cnpj, tipo, segmento, cidade, estado, is_active").order("name").limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,codigo.ilike.%${search}%,cnpj.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads do CRM, com filtro opcional por status e busca por nome/empresa.",
  inputSchema: {
    search: z4.string().trim().optional().describe("Texto para buscar em nome ou empresa."),
    status: z4.string().trim().optional().describe("Filtra por status exato do lead."),
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("id, codigo, name, company, email, phone, status, origin, servico, valor, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Registrar lead",
  description: "Registra uma nova demanda comercial como lead no CRM (regra: toda demanda de entrada vira lead).",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Nome do contato ou da demanda."),
    company: z5.string().trim().optional().describe("Empresa do contato."),
    email: z5.string().trim().email().optional(),
    phone: z5.string().trim().optional(),
    servico: z5.string().trim().optional().describe("Servi\xE7o solicitado."),
    location: z5.string().trim().optional().describe("Local do servi\xE7o."),
    origin: z5.string().trim().optional().describe("Origem da demanda."),
    notes: z5.string().trim().optional().describe("Observa\xE7\xF5es livres.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").insert({ ...input, responsible_id: ctx.getUserId() }).select("id, codigo, name, company, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool6({
  name: "list_alerts",
  title: "Listar alertas",
  description: "Lista alertas do sistema (pendentes por padr\xE3o), com filtro por prioridade.",
  inputSchema: {
    only_unresolved: z6.boolean().default(true).describe("Se true, retorna apenas alertas n\xE3o resolvidos."),
    priority: z6.enum(["urgente", "importante", "informacao"]).optional(),
    limit: z6.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_unresolved, priority, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("alerts").select("id, title, message, priority, alert_type, reference_type, reference_id, action_url, resolved, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_unresolved !== false) query = query.eq("resolved", false);
    if (priority) query = query.eq("priority", priority);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/resolve-alert.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var resolve_alert_default = defineTool7({
  name: "resolve_alert",
  title: "Resolver alerta",
  description: "D\xE1 baixa em um alerta do Radar depois que a a\xE7\xE3o foi executada. Exige descrever o que foi feito. S\xF3 pode ser usada pelo setor destinat\xE1rio do alerta (ou diretoria). Alerta que pede emiss\xE3o de nota/recibo n\xE3o pode ser baixado aqui: registre o t\xEDtulo com create_titulo, que o alerta fecha sozinho.",
  inputSchema: {
    alerta_id: z7.string().uuid().describe("UUID do alerta, obtido em list_alerts."),
    resolucao: z7.string().trim().min(5).describe("O que foi feito para resolver. Vai para o registro de auditoria."),
    origem_ref: z7.string().trim().optional().describe("Documento que justificou a baixa (Message-ID do e-mail, caminho no Drive).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ alerta_id, resolucao, origem_ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_resolve_alert", {
      p_alert_id: alerta_id,
      p_resolucao: resolucao,
      p_origem_ref: origem_ref ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var update_lead_status_default = defineTool8({
  name: "update_lead_status",
  title: "Mover lead no funil",
  description: "Move um lead para outro status do funil comercial. Use ao confirmar contato, envio de proposta, negocia\xE7\xE3o, perda ou descarte. Perda e descarte exigem motivo. Para transformar lead em projeto use o fluxo de convers\xE3o \u2014 o status convertido n\xE3o se digita.",
  inputSchema: {
    lead_id: z8.string().uuid().describe("UUID do lead, obtido em list_leads."),
    novo_status: z8.enum([
      "novo",
      "em_contato",
      "qualificado",
      "proposta_enviada",
      "em_negociacao",
      "aprovado",
      "perdido",
      "descartado"
    ]).describe("Novo status do funil. 'convertido' n\xE3o entra aqui \u2014 \xE9 resultado da convers\xE3o em projeto."),
    observacao: z8.string().trim().optional().describe("Motivo/observa\xE7\xE3o. Obrigat\xF3rio em 'perdido' e 'descartado'."),
    origem_ref: z8.string().trim().optional().describe("Documento que justificou a mudan\xE7a (Message-ID do e-mail, caminho no Drive).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, novo_status, observacao, origem_ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_update_lead_status", {
      p_lead_id: lead_id,
      p_novo_status: novo_status,
      p_observacao: observacao ?? null,
      p_origem_ref: origem_ref ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/tools/create-titulo.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var create_titulo_default = defineTool9({
  name: "create_titulo",
  title: "Registrar t\xEDtulo (NF ou recibo)",
  description: "Registra no Financeiro uma nota fiscal ou recibo de um projeto \u2014 o t\xEDtulo a receber. Empresa emissora e CNPJ do tomador v\xEAm do contrato do projeto e do cadastro do cliente; n\xE3o se escolhe na m\xE3o. Sem n\xFAmero de nota, o t\xEDtulo nasce pendente (a emitir); com n\xFAmero, nasce emitida e o projeto avan\xE7a para faturamento. Se havia alerta pedindo a emiss\xE3o, ele \xE9 resolvido automaticamente. origem_ref \xE9 obrigat\xF3rio: identifica o e-mail ou arquivo que originou o lan\xE7amento e impede que a mesma nota vire dois t\xEDtulos.",
  inputSchema: {
    projeto_codigo: z9.string().trim().min(1).describe("C\xF3digo do projeto, ex.: 2026-VIM-002."),
    valor_bruto: z9.number().positive().describe("Valor bruto do t\xEDtulo."),
    origem_ref: z9.string().trim().min(1).describe("Documento de origem (Message-ID do e-mail, caminho no Drive). Chave de idempot\xEAncia."),
    tipo: z9.enum(["nf", "recibo"]).optional().describe("Tipo do documento. Se omitido, usa o tipo do projeto."),
    nf_numero: z9.string().trim().optional().describe("N\xFAmero da nota. Ausente \u21D2 t\xEDtulo a emitir (pendente)."),
    nf_data: z9.string().trim().optional().describe("Data de emiss\xE3o (ISO, ex.: 2026-05-31). Obrigat\xF3ria se houver nf_numero."),
    vencimento: z9.string().trim().optional().describe("Data de vencimento (ISO). Deixar vazio se n\xE3o souber \u2014 n\xE3o estimar."),
    retencao: z9.number().min(0).optional().describe("Valor da reten\xE7\xE3o. Default 0."),
    cnpj_tomador: z9.string().trim().optional().describe("Apenas para confer\xEAncia; divergir do cadastro do cliente \xE9 erro."),
    observacoes: z9.string().trim().optional(),
    recarga: z9.boolean().optional().describe("Default false. true suprime alertas/e-mails autom\xE1ticos (Fase 0 de recarga).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ projeto_codigo, valor_bruto, origem_ref, tipo, nf_numero, nf_data, vencimento, retencao, cnpj_tomador, observacoes, recarga }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_create_titulo", {
      p_projeto_codigo: projeto_codigo,
      p_valor_bruto: valor_bruto,
      p_origem_ref: origem_ref,
      p_tipo: tipo ?? null,
      p_nf_numero: nf_numero ?? null,
      p_nf_data: nf_data ?? null,
      p_vencimento: vencimento ?? null,
      p_retencao: retencao ?? null,
      p_cnpj_tomador: cnpj_tomador ?? null,
      p_observacoes: observacoes ?? null,
      p_recarga: recarga ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/tools/register-recebimento.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^3.25.76";
var register_recebimento_default = defineTool10({
  name: "register_recebimento",
  title: "Registrar dinheiro que entrou",
  description: "Registra um recebimento: dinheiro que entrou na conta, do cliente X, no dia D. O recebimento pertence ao cliente, n\xE3o a uma nota \u2014 por isso funciona mesmo quando o cliente adianta antes de a nota existir, ou paga um valor que n\xE3o corresponde a t\xEDtulo nenhum. Se voc\xEA sabe a que t\xEDtulo(s) o dinheiro se refere, informe em alocacoes; o que sobrar fica como cr\xE9dito do cliente e pode ser abatido depois com allocate_recebimento. Se n\xE3o sabe, n\xE3o invente: registre sem aloca\xE7\xE3o. referencia_pagamento \xE9 a linha do extrato ou o identificador do comprovante \u2014 \xE9 ela que impede que o mesmo cr\xE9dito entre duas vezes. T\xEDtulo n\xE3o se marca como pago: ele fica quitado sozinho quando a soma das aloca\xE7\xF5es cobre o valor.",
  inputSchema: {
    cliente_id: z10.string().uuid().describe("UUID do cliente (de list_clients). Dinheiro sem dono n\xE3o entra."),
    valor: z10.number().positive().describe("O que caiu na conta."),
    data_recebimento: z10.string().trim().describe("Data real do cr\xE9dito (ISO). Futuro \xE9 recusado."),
    referencia_pagamento: z10.string().trim().min(1).describe("Linha do extrato / identificador do comprovante. \xDAnica no sistema \u2014 trava de dupla baixa."),
    empresa_recebedora: z10.enum(["ag_topografia", "ag_cartografia"]).describe("Em qual PJ o dinheiro caiu. ag_topografia = GONZAGA E BERLIM (16.841.054/0001-10); ag_cartografia = AG CARTOGRAFIA (48.282.440/0001-05)."),
    alocacoes: z10.array(z10.object({ titulo_id: z10.string().uuid(), valor: z10.number().positive() })).optional().describe("V\xEDnculos {titulo_id, valor}. Vazio \u21D2 cr\xE9dito puro (adiantamento)."),
    conta: z10.string().trim().optional().describe("Bradesco, BB Gonzaga, BB Cartografia."),
    origem_ref: z10.string().trim().optional().describe("Extrato/comprovante de origem."),
    observacoes: z10.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ cliente_id, valor, data_recebimento, referencia_pagamento, empresa_recebedora, alocacoes, conta, origem_ref, observacoes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_register_recebimento", {
      p_cliente_id: cliente_id,
      p_valor: valor,
      p_data_recebimento: data_recebimento,
      p_referencia_pagamento: referencia_pagamento,
      p_empresa_recebedora: empresa_recebedora,
      p_alocacoes: alocacoes ?? [],
      p_conta: conta ?? null,
      p_origem_ref: origem_ref ?? null,
      p_observacoes: observacoes ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/tools/allocate-recebimento.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z11 } from "npm:zod@^3.25.76";
var allocate_recebimento_default = defineTool11({
  name: "allocate_recebimento",
  title: "Dizer a que nota o dinheiro se refere",
  description: "Vincula dinheiro j\xE1 recebido a um ou mais t\xEDtulos. Use quando o cliente tinha adiantado e a nota saiu depois, ou quando voc\xEA descobriu a que se referia um cr\xE9dito antigo. N\xE3o altera o recebimento nem o t\xEDtulo: cria o v\xEDnculo, e o saldo se recalcula sozinho. Um recebimento s\xF3 aloca uma vez para cada t\xEDtulo \u2014 chamar de novo devolve ja_alocado sem duplicar.",
  inputSchema: {
    recebimento_id: z11.string().uuid().describe("UUID do recebimento (de register_recebimento ou da consulta de cr\xE9dito)."),
    alocacoes: z11.array(z11.object({ titulo_id: z11.string().uuid(), valor: z11.number().positive() })).min(1).describe("V\xEDnculos {titulo_id, valor}. Pelo menos um item."),
    origem_ref: z11.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ recebimento_id, alocacoes, origem_ref }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_allocate_recebimento", {
      p_recebimento_id: recebimento_id,
      p_alocacoes: alocacoes,
      p_origem_ref: origem_ref ?? null
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/tools/update-execution-status.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z12 } from "npm:zod@^3.25.76";
var update_execution_status_default = defineTool12({
  name: "update_execution_status",
  title: "Atualizar status de execu\xE7\xE3o do projeto",
  description: "Move o status de execu\xE7\xE3o de um projeto \u2014 campo, processamento, revis\xE3o, aprova\xE7\xE3o, entrega. Informe data_efetiva com a data real do fato, n\xE3o a de hoje: \xE9 isso que mant\xE9m o hist\xF3rico correto ao registrar acontecimentos passados. Voltar para um status anterior \xE9 corre\xE7\xE3o e exige motivo. faturamento e pago n\xE3o entram aqui \u2014 v\xEAm de create_titulo e do recebimento alocado.",
  inputSchema: {
    projeto_codigo: z12.string().trim().min(1).describe("C\xF3digo do projeto."),
    novo_status: z12.enum([
      "aguardando_campo",
      "em_campo",
      "campo_concluido",
      "aguardando_processamento",
      "em_processamento",
      "revisao",
      "aprovado",
      "entregue"
    ]).describe("Novo status de execu\xE7\xE3o. 'faturamento' e 'pago' n\xE3o entram aqui."),
    data_efetiva: z12.string().trim().optional().describe("Data real do fato (ISO). Default hoje; futuro \xE9 recusado."),
    motivo: z12.string().trim().optional().describe("Obrigat\xF3rio em retrocesso (voltar a status anterior)."),
    origem_ref: z12.string().trim().optional(),
    recarga: z12.boolean().optional().describe("Default false. true suprime alertas/e-mails autom\xE1ticos (Fase 0 de recarga).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ projeto_codigo, novo_status, data_efetiva, motivo, origem_ref, recarga }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("fn_update_execution_status", {
      p_projeto_codigo: projeto_codigo,
      p_novo_status: novo_status,
      p_data_efetiva: data_efetiva ?? null,
      p_motivo: motivo ?? null,
      p_origem_ref: origem_ref ?? null,
      p_recarga: recarga ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { resultado: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bphgtvwgsgaqaxmkrtqj";
var mcp_default = defineMcp({
  name: "ag-central-flow",
  title: "AG Central Flow",
  version: "0.1.0",
  instructions: "Ferramentas do Sistema AG (topografia e cartografia). Consulte projetos, clientes, leads e alertas, e registre novas demandas comerciais como leads. Todas as chamadas rodam como o usu\xE1rio autenticado, respeitando as permiss\xF5es dele.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_clients_default,
    list_leads_default,
    create_lead_default,
    list_alerts_default,
    resolve_alert_default,
    update_lead_status_default,
    create_titulo_default,
    register_recebimento_default,
    allocate_recebimento_default,
    update_execution_status_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
