// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Listar projetos",
  description: "Lista projetos do sistema AG, com filtro opcional por texto (nome/c\xF3digo) e por status de execu\xE7\xE3o.",
  inputSchema: {
    search: z.string().trim().optional().describe("Texto para buscar em nome ou c\xF3digo do projeto."),
    execution_status: z.string().trim().optional().describe("Filtra por execution_status exato (ex: em_campo, entregue, faturamento)."),
    limit: z.number().int().min(1).max(100).default(20).describe("M\xE1ximo de projetos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, execution_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id, codigo, name, service, status, execution_status, contract_value, client_id, delivery_deadline").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,codigo.ilike.%${search}%`);
    if (execution_status) query = query.eq("execution_status", execution_status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Detalhe do projeto",
  description: "Retorna os dados completos de um projeto pelo c\xF3digo (ex: 2026-AGT-001) ou pelo id.",
  inputSchema: {
    codigo: z2.string().trim().optional().describe("C\xF3digo do projeto."),
    id: z2.string().uuid().optional().describe("UUID do projeto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ codigo, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    if (!codigo && !id) {
      return { content: [{ type: "text", text: "Informe codigo ou id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("*").limit(1);
    query = id ? query.eq("id", id) : query.eq("codigo", codigo);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Projeto n\xE3o encontrado." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_clients_default = defineTool3({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes cadastrados, com busca opcional por nome, c\xF3digo de 3 letras ou CNPJ.",
  inputSchema: {
    search: z3.string().trim().optional().describe("Texto para buscar em nome, c\xF3digo ou CNPJ."),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, codigo, name, cnpj, tipo, segmento, cidade, estado, is_active").order("name").limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,codigo.ilike.%${search}%,cnpj.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads do CRM, com filtro opcional por status e busca por nome/empresa.",
  inputSchema: {
    search: z4.string().trim().optional().describe("Texto para buscar em nome ou empresa."),
    status: z4.string().trim().optional().describe("Filtra por status exato do lead."),
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("id, codigo, name, company, email, phone, status, origin, servico, valor, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.or(`name.ilike.%${search}%,company.ilike.%${search}%`);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Registrar lead",
  description: "Registra uma nova demanda comercial como lead no CRM (regra: toda demanda de entrada vira lead).",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Nome do contato ou da demanda."),
    company: z5.string().trim().optional().describe("Empresa do contato."),
    email: z5.string().trim().email().optional(),
    phone: z5.string().trim().optional(),
    servico: z5.string().trim().optional().describe("Servi\xE7o solicitado."),
    location: z5.string().trim().optional().describe("Local do servi\xE7o."),
    origin: z5.string().trim().optional().describe("Origem da demanda."),
    notes: z5.string().trim().optional().describe("Observa\xE7\xF5es livres.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("leads").insert({ ...input, responsible_id: ctx.getUserId() }).select("id, codigo, name, company, status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_alerts_default = defineTool6({
  name: "list_alerts",
  title: "Listar alertas",
  description: "Lista alertas do sistema (pendentes por padr\xE3o), com filtro por prioridade.",
  inputSchema: {
    only_unresolved: z6.boolean().default(true).describe("Se true, retorna apenas alertas n\xE3o resolvidos."),
    priority: z6.enum(["urgente", "importante", "informacao"]).optional(),
    limit: z6.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_unresolved, priority, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("alerts").select("id, title, message, priority, alert_type, reference_type, reference_id, action_url, resolved, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_unresolved !== false) query = query.eq("resolved", false);
    if (priority) query = query.eq("priority", priority);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bphgtvwgsgaqaxmkrtqj";
var mcp_default = defineMcp({
  name: "ag-central-flow",
  title: "AG Central Flow",
  version: "0.1.0",
  instructions: "Ferramentas do Sistema AG (topografia e cartografia). Consulte projetos, clientes, leads e alertas, e registre novas demandas comerciais como leads. Todas as chamadas rodam como o usu\xE1rio autenticado, respeitando as permiss\xF5es dele.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_clients_default,
    list_leads_default,
    create_lead_default,
    list_alerts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
